"""Fixtures for the historical-market suite.

Every file these tests read is generated by ``make_fixtures.py`` in a tmp
directory. **No downloaded vendor data is used by any test**: the two Kibot
samples live in the gitignored download directory and are read only by
``experiments/historical/run.py``.
"""
from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
UPSTREAM = ROOT / "upstream"
REAL_DATA = ROOT / "data" / "malecns-v1.0"

for p in (str(ROOT), str(UPSTREAM)):
    if p not in sys.path:
        sys.path.insert(0, p)

from tests.historical import make_fixtures as MF     # noqa: E402

DAYS = MF.DAYS


def has_real_graph() -> bool:
    return all((REAL_DATA / f).exists() for f in
               ("graph.npz", "graph_mod.npz", "annotations.npz"))


requires_real_graph = pytest.mark.skipif(
    not has_real_graph(),
    reason="built connectome absent; see data/MANIFEST.md")


@pytest.fixture(scope="session")
def fixtures(tmp_path_factory):
    """Every vendor-shaped fixture file, generated by the committed script."""
    return MF.write_all(tmp_path_factory.mktemp("vendor"))


@pytest.fixture(scope="session")
def series_a(fixtures):
    from flytrade import historical as H
    return H.load_series(fixtures["A"], "A")


@pytest.fixture(scope="session")
def series_b(fixtures):
    from flytrade import historical as H
    return H.load_series(fixtures["B"], "B")


@pytest.fixture(scope="session")
def universe(series_a, series_b):
    return {"A": series_a, "B": series_b}


@pytest.fixture(scope="session")
def ann():
    if not has_real_graph():
        pytest.skip("built connectome absent")
    from flytrade import populations as P
    return P.Annotations.load(REAL_DATA / "annotations.npz")


@pytest.fixture(scope="session")
def brain(ann):
    """(FlyBrain, MushroomBody, gains) over the real connectome."""
    import numpy as np
    import flysim
    from flytrade import encoder as E, graph as G, mushroom as M, populations as P
    fb = flysim.FlyBrain(graph_path=REAL_DATA / "graph.npz")
    mod = G.ModulatoryGraph(REAL_DATA / "graph_mod.npz", bodies=fb.bodies)
    mb = M.MushroomBody(fb, mod,
                        np.flatnonzero(P.kenyon_cells(ann)),
                        np.flatnonzero(P.mbons(ann)),
                        np.flatnonzero(P.pam(ann)),
                        np.flatnonzero(P.ppl1(ann)))
    gains = np.full(fb.n_types, E.GLOBAL_GAIN, dtype=np.float32)
    return fb, mb, gains


@pytest.fixture(scope="session")
def graph_sha256():
    from flytrade import graph as G
    return G.sha256_file(REAL_DATA / "graph.npz")


@pytest.fixture
def fresh_weights(brain):
    """Reset learned gains and traces around a test that changes them."""
    fb, mb, _ = brain
    mb.gain[:] = 1.0
    mb.trace[:] = 0.0
    mb.trace_episode[:] = -1
    mb.events = {"reward": 0, "punish": 0, "rejected_episode": 0}
    mb.apply()
    yield mb
    mb.gain[:] = 1.0
    mb.trace[:] = 0.0
    mb.trace_episode[:] = -1
    mb.apply()
