"""Fixtures for the D9(b) suite.

Every price file these tests read is generated by
``tests/historical/make_fixtures.py`` in a tmp directory. **No downloaded
vendor data is used by any test**: the Kibot sample lives in the gitignored
download directory and is read only by the scripts under ``experiments/``.

The connectome follows the house convention: the tests that need the built
graph carry ``requires_real_graph`` and skip without it.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
UPSTREAM = ROOT / "upstream"
REAL_DATA = ROOT / "data" / "malecns-v1.0"

for p in (str(ROOT), str(UPSTREAM), str(ROOT / "experiments" / "historical")):
    if p not in sys.path:
        sys.path.insert(0, p)

from tests.historical import make_fixtures as MF     # noqa: E402

DAYS = MF.DAYS


def has_real_graph() -> bool:
    return all((REAL_DATA / f).exists() for f in
               ("graph.npz", "graph_mod.npz", "annotations.npz"))


requires_real_graph = pytest.mark.skipif(
    not has_real_graph(),
    reason="built connectome absent; see data/MANIFEST.md")


@pytest.fixture(scope="session")
def fixtures(tmp_path_factory):
    return MF.write_all(tmp_path_factory.mktemp("vendor-d9b"))


@pytest.fixture(scope="session")
def series_a(fixtures):
    from flytrade import historical as H
    return H.load_series(fixtures["A"], "A")


@pytest.fixture(scope="session")
def series_b(fixtures):
    from flytrade import historical as H
    return H.load_series(fixtures["B"], "B")


@pytest.fixture(scope="session")
def universe(series_a, series_b):
    return {"A": series_a, "B": series_b}


@pytest.fixture(scope="session")
def ann():
    if not has_real_graph():
        pytest.skip("built connectome absent")
    from flytrade import populations as P
    return P.Annotations.load(REAL_DATA / "annotations.npz")


@pytest.fixture(scope="session")
def graph_sha256():
    from flytrade import graph as G
    return G.sha256_file(REAL_DATA / "graph.npz")


@pytest.fixture(scope="session")
def brain(ann):
    """(FlyBrain, MushroomBody, encoder, populations) over the real graph."""
    import numpy as np
    import flysim
    from flytrade import encoder as E, graph as G, mushroom as M
    from flytrade import populations as P, decoder as D
    fb = flysim.FlyBrain(graph_path=REAL_DATA / "graph.npz")
    mod = G.ModulatoryGraph(REAL_DATA / "graph_mod.npz", bodies=fb.bodies)
    mb = M.MushroomBody(fb, mod,
                        np.flatnonzero(P.kenyon_cells(ann)),
                        np.flatnonzero(P.mbons(ann)),
                        np.flatnonzero(P.pam(ann)),
                        np.flatnonzero(P.ppl1(ann)))
    enc = E.MarketToSensoryEncoder(ann)
    pops = D.readout_populations(ann, mb.compartments)
    return fb, mb, enc, pops


@pytest.fixture
def runner(brain, graph_sha256):
    """A fresh-weight :class:`flytrade.runner.BrainRunner` over the real graph."""
    from flytrade import runner as R
    fb, mb, enc, pops = brain
    mb.gain[:] = 1.0
    mb.trace[:] = 0.0
    mb.trace_episode[:] = -1
    mb.events = {"reward": 0, "punish": 0, "rejected_episode": 0}
    mb.apply()
    yield R.BrainRunner(fb, mb, enc, pops, graph_sha256=graph_sha256)
    mb.gain[:] = 1.0
    mb.trace[:] = 0.0
    mb.trace_episode[:] = -1
    mb.apply()
