"""Fixtures for the D8 suite.

Every price file these tests read is generated by ``make_fixtures.py`` in a tmp
directory. **No downloaded vendor data is used by any test**: the Kibot sample
lives in the gitignored download directory and is read only by the scripts under
``experiments/d8/``.

scikit-learn is imported directly by the D8 tests, with no ``importorskip``
(Fable addendum 7): a missing ``diagnostics`` extra must fail the gate loudly,
never skip it. The connectome follows the house convention instead — the tests
that need the built annotations carry ``requires_real_graph``.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
UPSTREAM = ROOT / "upstream"
REAL_DATA = ROOT / "data" / "malecns-v1.0"
D8 = ROOT / "experiments" / "d8"

for p in (str(ROOT), str(UPSTREAM), str(D8)):
    if p not in sys.path:
        sys.path.insert(0, p)

from tests.d8 import make_fixtures as MF        # noqa: E402


def has_real_graph() -> bool:
    return (REAL_DATA / "annotations.npz").exists()


requires_real_graph = pytest.mark.skipif(
    not has_real_graph(), reason="built connectome absent; see data/MANIFEST.md")


@pytest.fixture(scope="session")
def fixtures(tmp_path_factory):
    """A clean vendor-shaped file and its future-perturbed twin."""
    return MF.write_all(tmp_path_factory.mktemp("vendor-d8"))


@pytest.fixture(scope="session")
def clean(fixtures):
    from flytrade import historical as H
    return H.load_series(fixtures["A"], "A")


@pytest.fixture(scope="session")
def future_changed(fixtures):
    """Byte-identical to ``clean`` up to the cut, different at every later bar."""
    from flytrade import historical as H
    return H.load_series(fixtures["F"], "F")


@pytest.fixture(scope="session")
def ann():
    if not has_real_graph():
        pytest.skip("built connectome absent")
    from flytrade import populations as P
    return P.Annotations.load(REAL_DATA / "annotations.npz")
