"""Fixtures for the D7 suite.

Every file these tests read is generated by ``make_fixtures.py`` in a tmp
directory. **No downloaded vendor data is used by any test**: the Kibot sample
lives in the gitignored download directory and is read only by
``experiments/d7/calibrate.py``, ``run.py`` and ``evaluate.py``.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
UPSTREAM = ROOT / "upstream"

for p in (str(ROOT), str(UPSTREAM), str(ROOT / "experiments" / "d7")):
    if p not in sys.path:
        sys.path.insert(0, p)

from tests.d7 import make_fixtures as MF      # noqa: E402

DAYS = MF.DAYS
WARMUP_DAYS = MF.WARMUP_DAYS
LATER_DAYS = MF.LATER_DAYS


@pytest.fixture(scope="session")
def fixtures(tmp_path_factory):
    """Every vendor-shaped fixture file, generated by the committed script."""
    return MF.write_all(tmp_path_factory.mktemp("vendor-d7"))


@pytest.fixture(scope="session")
def clean(fixtures):
    from flytrade import historical as H
    return H.load_series(fixtures["W"], "W")


@pytest.fixture(scope="session")
def perturbed(fixtures):
    """Identical to ``clean`` inside the WARMUP dates, different after them."""
    from flytrade import historical as H
    return H.load_series(fixtures["P"], "P")


@pytest.fixture(scope="session")
def gapped(fixtures):
    from flytrade import historical as H
    return H.load_series(fixtures["G"], "G")
